## numpy gives us tha data structure in form of (array)numpy=numerical python array handle large amount of data


In [412]:
d=[400,300,200,100]
sp=[40,50,60,70]
l=list(zip(d,sp))
l

[(400, 40), (300, 50), (200, 60), (100, 70)]

In [413]:
main=[]
for i in l:
    l1=[]
    for j in i:
        l1.append(j)
    main.append(l1)
main    

[[400, 40], [300, 50], [200, 60], [100, 70]]

In [414]:
time=[]
for k in main:
    time.append(k[0]/k[1])
print(time)

[10.0, 6.0, 3.3333333333333335, 1.4285714285714286]


In [415]:
import numpy as np
d1=np.array([400,300,200,100])
sp1=np.array([40,50,70,60])
d1/sp1

array([10.        ,  6.        ,  2.85714286,  1.66666667])

### ndarry=n dimensional array(core data structure of numpy)array
**stores homogenious data
**fast and efficient
**

from python str like list and tuple

In [416]:
a=np.array([1,2,3,4,5])  ## array creation from list
type(a)
a.dtype

dtype('int32')

In [417]:
a=np.array([1.1,1.2,3.2,4.2,5])      ## array creation from list
type(a)
a.dtype

dtype('float64')

In [418]:
a2=np.array([[20,30,46],[30,40,50]])      ### array creat in 2 dimension list:
a2

array([[20, 30, 46],
       [30, 40, 50]])

In [419]:
a2=np.array([[[20,30,46],[30,40,50],[20,39,40]]])    ### array creat in  3 dimension list:
a2
a2.dtype


dtype('int32')

In [420]:
a1=np.array((20,30,40))
a1

array([20, 30, 40])

In [421]:
a1=np.array("hello") ## ita zeroth dimensional#
a1
a1.ndim

0

## importtant property of ndarray

*ndim
*shape
*size
*


In [422]:
print(np.array([20,30,40]))     ## single dimension array
a1=np.array([20,30,40])
a1.ndim


[20 30 40]


1

In [423]:
c=np.array([[1, 2, 3], [4, 5, 6]]) ## 2D array
c.ndim

2

In [424]:
c= np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])#### 3D array
c.ndim

3

In [425]:
import numpy as np
e= np.array([[[[[[[2,3,4,5,6]]]]]]])
e.ndim

7

In [426]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5]) # in  single dimension we can not judge the rows and columns
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e=np.array([[[[1, 2, 3], [4, 5, 6]]]])
f=np.array([[2,3,4,5]])
g=np.array([[[[[20,30]]]]])
print(a.ndim)
print(np.ndim(a))
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)
print(f.ndim)
print(g.ndim)





0
0
1
2
3
4
2
5


In [427]:
a1=np.array([1,2,3,4],ndmin=5)   ### change dimension by by giving value
a1

array([[[[[1, 2, 3, 4]]]]])

In [428]:
a1=np.array([[1,2,3],[20,30,40],[30,40,50]],ndmin=7)
a1

array([[[[[[[ 1,  2,  3],
            [20, 30, 40],
            [30, 40, 50]]]]]]])

## shape (number of elements present in each dimension)

In [429]:
## shape of 1D

a=np.array([1,2,3])   ## we can not judge how rows and columns(thats why comma occer)
print(a.shape)

(3,)


In [430]:
a=np.array([[2,4,5,5],[4,5,6,7]])
a.shape

(2, 4)

In [431]:
a=np.array([[[2,4,5,5],[4,5,6,7],[2,3,4,5]]])
a.shape

(1, 3, 4)

In [432]:
a=np.array([[1,2,35,5]])
a.shape

(1, 4)

In [433]:
a=np.array([])
a.shape

(0,)

In [434]:
a=np.array([[2,4,5,5],[4,5,6,7]])
a.shape

(2, 4)

In [435]:
k=np.array([[[[[[[2,3,4],[45,78,90],[50,90,89]]]]]]])
print(k.shape)
c


(1, 1, 1, 1, 1, 3, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [436]:
import numpy as np
k=np.array([[[[[[[2,3,4],[45,78,90],[50,90,89]]]]]]])
print(k.shape)

(1, 1, 1, 1, 1, 3, 3)


In [437]:
import numpy as np
a=np.array([[[[[[[["pizza","sweet corn","coffee","lemonade"]]]]]]]])
a.shape

(1, 1, 1, 1, 1, 1, 1, 4)

In [438]:
import numpy as np
lst=[1,2,3,4]
arr=np.array(lst)
arr

array([1, 2, 3, 4])

In [439]:
type(arr)

numpy.ndarray

In [440]:
arr.shape

(4,)

In [441]:
arr.ndim

1

In [442]:
arr.dtype

dtype('int32')

In [443]:
a

array([[[[[[[['pizza', 'sweet corn', 'coffee', 'lemonade']]]]]]]],
      dtype='<U10')

In [444]:
a.shape

(1, 1, 1, 1, 1, 1, 1, 4)

In [445]:
a.ndim

8

In [446]:
## indexing
arr

array([1, 2, 3, 4])

In [447]:
arr[3]

4

In [448]:
arr[3]=8
arr

array([1, 2, 3, 8])

In [449]:
arr[-1]

8

In [450]:
arr[:-1]

array([1, 2, 3])

In [451]:
arr[::-1]

array([8, 3, 2, 1])

In [452]:
arr[::-2]

array([8, 2])

In [453]:
a=np.array([[1,2,3,4],[5,6,7,8],[3,4,5,6]])
a
print(a)

[[1 2 3 4]
 [5 6 7 8]
 [3 4 5 6]]


In [454]:
a[1:,1:4]

array([[6, 7, 8],
       [4, 5, 6]])

In [455]:
a[0:,1:4]

array([[2, 3, 4],
       [6, 7, 8],
       [4, 5, 6]])

In [456]:
a[0:,0:1]

array([[1],
       [5],
       [3]])

In [457]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 4, 5, 6]])

In [458]:
a[:,2:]

array([[3, 4],
       [7, 8],
       [5, 6]])

In [459]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 4, 5, 6]])

In [460]:
a[0:,0:1]

array([[1],
       [5],
       [3]])

### EDA (exploratary data analysis)

In [461]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 4, 5, 6]])

In [462]:
a>3

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [False,  True,  True,  True]])

In [463]:
arr

array([1, 2, 3, 8])

In [464]:
arr<3

array([ True,  True, False, False])

In [465]:
a1=[arr<4]
a1

[array([ True,  True,  True, False])]

In [466]:
a1

[array([ True,  True,  True, False])]

In [467]:
list1=[1,2,3,4,5]
list2=[2,3,0,5,6]
list3=[2,0,4,5,6]
arr=np.array([list1,list2,list3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 0, 5, 6],
       [2, 0, 4, 5, 6]])

In [468]:
arr[0:3:2,0:1:2]

array([[1],
       [2]])

In [469]:
arr[1:,0:2]

array([[2, 3],
       [2, 0]])

In [470]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 0, 5, 6],
       [2, 0, 4, 5, 6]])

In [471]:
arr[0:3,1:]

array([[2, 3, 4, 5],
       [3, 0, 5, 6],
       [0, 4, 5, 6]])

In [472]:
arr[1:,3:]

array([[5, 6],
       [5, 6]])

In [473]:
arr.shape

(3, 5)

In [474]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 0, 5],
       [6, 2, 0],
       [4, 5, 6]])

In [475]:
### to create  array
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [476]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [477]:
np.arange(1,20,2).reshape(1,10)

array([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

In [478]:
np.arange(1,20,2).reshape(1,5,2)

array([[[ 1,  3],
        [ 5,  7],
        [ 9, 11],
        [13, 15],
        [17, 19]]])

In [479]:
a=np.arange(1,20,2).reshape(1,10,1)
a

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11],
        [13],
        [15],
        [17],
        [19]]])

In [480]:
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [481]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 0, 5, 6],
       [2, 0, 4, 5, 6]])

In [482]:
arr[:,::4]

array([[1, 5],
       [2, 6],
       [2, 6]])

In [483]:
arr[:,::3]

array([[1, 4],
       [2, 5],
       [2, 5]])

In [484]:
arr*arr

array([[ 1,  4,  9, 16, 25],
       [ 4,  9,  0, 25, 36],
       [ 4,  0, 16, 25, 36]])

In [485]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [486]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [487]:
np.random.randint(2,40,5)

array([25, 30, 37, 37, 18])

In [488]:
np.random.randint(2,40,4).reshape(2,2)

array([[35,  4],
       [ 8, 39]])

In [489]:
np.random.randn(2,5)

array([[-0.06798036, -1.1849607 , -3.27152882, -0.8746591 ,  1.11828039],
       [-1.02853183,  0.42103779,  0.52186904, -0.13609885,  1.42770594]])

## size create an array of shape 2,4,2

In [492]:
a=np.array([[[1,2],[3,4],[5,6],[7,8]],[[9,10],[11,12],[13,14],[15,16]]])
a.shape

(2, 4, 2)

In [493]:
import numpy as np
k=np.array([[[[[[[2,3,4],[45,78,90],[50,90,89]]]]]]])
print(k.shape)
[]

(1, 1, 1, 1, 1, 3, 3)


[]

 ## create array of (1,1,3,3)

In [495]:
import numpy as np
a1=np.array([[[[1,2,3],[4,5,6],[5,6,7]]]])
a1.shape

(1, 1, 3, 3)

In [496]:
import numpy as np# create an array of 1,1,3,3,3
a1=np.array([[[[[1,2,3],[1,1,1],[1,1,1]],[[1,1,1],[1,1,1],[1,1,1]],[[1,1,1],[1,1,1],[1,1,1]]]]])
a1.shape

(1, 1, 3, 3, 3)

In [497]:
a1.ndim  ##(rank and dimension are same)

5

## size of array

In [499]:
a=np.array([[20,30,40,50]])
np.size(a)
a.shape

(1, 4)

In [500]:
a.ndim

2

In [501]:
print(np.size(a,axis=0))

1


In [502]:
a=np.array([[1,2,3,4],[4,5,6,7]])
print(np.size(a))
print(np.size(a,0))
print(np.size(a,1))

8
2
4


In [503]:
a=np.array([[[1,2,1,1],[1,2,3,4]],[[1,1,1,1],[1,1,1,1]]])
print(np.size(a))

16


## itemsize: represent memoery occupied  by each  element in bytes

In [504]:
l=[1,2,3]
a=np.array(l)
print(a.dtype) ### int32 means 4bytes 4*8bytes =32 bits
print(a.itemsize)
print(a.size*a.itemsize) ## total memory occupied by array

int32
4
12


In [505]:
a=np.ones((2,3))
print(a)
a.dtype ## by default : float

[[1. 1. 1.]
 [1. 1. 1.]]


dtype('float64')

In [506]:
a=np.ones((2,3,1)) ## to create array of shape (2,3,1)
print(a)
a.dtype

[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]


dtype('float64')

## 'ASTYPE : CONVERT THA EXISTING DTYPE TO ANOTHER

In [507]:
a1=a.astype("int") ### float to int
a1


array([[[1],
        [1],
        [1]],

       [[1],
        [1],
        [1]]])

In [508]:
import sys
l=list(range(100))
a=np.arange(100)
print(sys.getsizeof(l))
print(a.itemsize)
print("list takes :",sys.getsizeof(l)*len(l),"bytes")  ##ys.getsizeof(l) : size of each element in the list
print("array takes : ",a.itemsize*a.size,"bytes" ) ## itemsize: size of each element in the array.



856
4
list takes : 85600 bytes
array takes :  400 bytes


## Array indexing

In [509]:
a=np.array([1,2,3,4])
a[0:4:3]

array([1, 4])

In [510]:
a=np.array([[2,3,4,5,6],[7,8,9,0,90],[20,30,40,50,90]])
a[0]

array([2, 3, 4, 5, 6])

In [511]:
a[-1]

array([20, 30, 40, 50, 90])

In [512]:
a[-1][2]

40

In [513]:
a[-1][3:]

array([50, 90])

In [514]:
a=np.array([[2,3,4,5,6],[7,8,9,0,90],[20,30,40,50,90]])
a[0]

array([2, 3, 4, 5, 6])

In [515]:
a[0:3:2,:]

array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 90]])

In [516]:
a

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9,  0, 90],
       [20, 30, 40, 50, 90]])

In [517]:
a[1:,1:3]

array([[ 8,  9],
       [30, 40]])

In [518]:
a=np.array([[2,3,4,5,6],[7,8,9,0,90],[20,30,40,50,90]])  # 2d array  here , 
print(a)
print(a[0]) #or print(a[-3]) means first row
print(a[1]) #or print(a[-2]) means second row
print(a[2]) #or print(a[-1]) means third row
print(a[-1]) # or print(a[2])  means  last row
print(a[0][2]) # fetch 4
print(a[1][2:]) # 9,0,90
print(a[-2][0])  # fetch 7
print(a[:,2])  ## all rows with 2nd column  (discontinous manner)
print(a[0:2,2:]) ## ist and 2nd rows with columns from 2nd(disconinous manner)
print(a[1,2:3])
print(a[0:3:2,2:5:2]) ## feth 4,6 40 ,90
#print(a[[0,2],[1,3]])
print(a[0:3:2,1:4:2]) ## fetch 3, 30 5 and 50
 


[[ 2  3  4  5  6]
 [ 7  8  9  0 90]
 [20 30 40 50 90]]
[2 3 4 5 6]
[ 7  8  9  0 90]
[20 30 40 50 90]
[20 30 40 50 90]
4
[ 9  0 90]
7
[ 4  9 40]
[[ 4  5  6]
 [ 9  0 90]]
[9]
[[ 4  6]
 [40 90]]
[[ 3  5]
 [30 50]]


In [519]:
a=np.array([[[[[[[["pizza","sweet corn","coffee","lemonade"]]]]]]]])
a[0][0][0][-1]

array([[[['pizza', 'sweet corn', 'coffee', 'lemonade']]]], dtype='<U10')

In [520]:
print(a[0][0][0][0][0][0][0][0])


pizza


In [521]:
a=np.array([[[[[1,2,3,50,],[4,5,6,90],[7,8,9,99],[11,12,3,98]]]]])
a[0][0][0][-1][-1]

98

In [522]:
a[0][0][0][3][-1]

98

In [523]:
a[0][0][0][0][2:]

array([ 3, 50])

In [524]:
a=np.array([[[[1,2,3,4,5],[6,7,8,9,0],[11,12,13,14,15],[16,17,18,19,20]]]])

a[0][0][-1][-2]

19

In [525]:
a[0][0][2][2:5:2]

array([13, 15])

In [526]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr[1][0]

array([7, 8, 9])

In [527]:
arr[1][0][1:3]

array([8, 9])

In [528]:
arr[1][1][1:3]

array([11, 12])

In [529]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [530]:
arr[1][:,1:]

array([[ 8,  9],
       [11, 12]])

## Indexing with boolean: from EDA point  of view

In [531]:
a=np.array([[20,30,60],[40,80,90],[70,90,100]])
a

array([[ 20,  30,  60],
       [ 40,  80,  90],
       [ 70,  90, 100]])

In [532]:
a<40

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [533]:
x=a<40
x

array([[ True,  True, False],
       [False, False, False],
       [False, False, False]])

In [534]:
a[x]

array([20, 30])

In [535]:
a[a<40]

array([20, 30])

In [536]:
np.where(a<40,"85","nothing")

array([['85', '85', 'nothing'],
       ['nothing', 'nothing', 'nothing'],
       ['nothing', 'nothing', 'nothing']], dtype='<U7')

## Double array (multi condition)

In [537]:
a[(a%2==0)&(a>40)]   ### And condition


array([ 60,  80,  90,  70,  90, 100])

In [538]:
a[(a%2==0)|(a>40)]   ### Or condition


array([ 20,  30,  60,  40,  80,  90,  70,  90, 100])

In [539]:
a[((a>40)|(a%2==0))]   ### Or condition


array([ 20,  30,  60,  40,  80,  90,  70,  90, 100])

In [540]:
a=[[[[2,3,4,5],[40,50,60,90]]]]
a=np.array(a)
a.ndim


4

In [541]:
a[0][0][ :,1]  ##,a[0][0][1][1:2]

array([ 3, 50])

In [542]:
a[0][0][[0,1],[1,3]]  ##,a[0][0][1][1:2]

array([ 3, 90])

In [543]:
a[0][0][[0,1],[1,2]]

array([ 3, 60])

In [544]:
a[0][0][[0,1],[1,-1]]

array([ 3, 90])

In [545]:
a[0][0][[0,1],[1,3]]  ##,a[0][0][1][1:2]

array([ 3, 90])

In [546]:
a[0][0][ :,-1]

array([ 5, 90])

In [547]:
a[0][0][1,2:]

array([60, 90])

In [548]:
a

array([[[[ 2,  3,  4,  5],
         [40, 50, 60, 90]]]])

In [549]:
print(a[0][0][:,3])

[ 5 90]


In [550]:
a=np.array([[1,2,3,12],[4,5,6,0],[6,7,8,9]])
a

array([[ 1,  2,  3, 12],
       [ 4,  5,  6,  0],
       [ 6,  7,  8,  9]])

In [551]:
a[2,[0,1,]]

array([6, 7])

## iteration  ( using : np.nditer())

In [554]:
a=np.array([[2,3,4],[5,6,7]])  
print(a)

[[2 3 4]
 [5 6 7]]


In [555]:
for i in np.nditer(a):
    print(i)

2
3
4
5
6
7


## COPY and VIEW:

In [556]:
a=np.array([2,3,4,5])
a1=a.copy()   ## deep copy
a1[3]=70
print("copy----",a1)
print("original array",a)

copy---- [ 2  3  4 70]
original array [2 3 4 5]


In [557]:
a=np.array([2,3,4,5])
a1=a.view()  ### shalow copy
a1[3]=70
print("copy----",a1)
print("original array",a)

copy---- [ 2  3  4 70]
original array [ 2  3  4 70]


In [558]:
a=np.array([2,3,4,5])
a2=a.copy()            ###  implicitly view occure
a2[2]="700"
print(a2)
print(a)

[  2   3 700   5]
[2 3 4 5]


## (reshape behaves like deep copy0  (resize behaves like a view)

In [559]:
x=np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
x

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [560]:
print(x.size)
print(x.shape)
x.ndim

12
(2, 6)


2

### how we rep (2,6) as(6,2),(3,4),(4,3),(12,1),(1,12)

In [561]:
x1=x.reshape(1,12)
print("deep copy",x1)
print("origion copy",x)

deep copy [[1 2 3 4 5 6 1 2 3 4 5 6]]
origion copy [[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [562]:
x1=x.reshape(6,2)
print("deep copy",x1)
print("origion copy",x)

deep copy [[1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]]
origion copy [[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [563]:
x1=x.resize(1,12)
print("deep copy",x1)
print("origion copy",x)

deep copy None
origion copy [[1 2 3 4 5 6 1 2 3 4 5 6]]


In [564]:
x1=x.reshape(3,4)
print("deep copy",x1)
print("origion copy",x)

deep copy [[1 2 3 4]
 [5 6 1 2]
 [3 4 5 6]]
origion copy [[1 2 3 4 5 6 1 2 3 4 5 6]]


In [565]:
x1=x.reshape(2,6)
print("deep copy",x1)
print("origion copy",x)

deep copy [[1 2 3 4 5 6]
 [1 2 3 4 5 6]]
origion copy [[1 2 3 4 5 6 1 2 3 4 5 6]]


In [566]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr)

newarr = arr.reshape(2, 2, -1)
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])



[1 2 3 4 5 6 7 8]


## (**flatten()  its treats as deep copy)  (**reshape(-1)) ( **ravel()  its treats as shalow copy)

In [567]:
arr=np.array([[1,2,3],[4,5,6,]])
arr1=arr.ravel()
print("1d----",arr1)
print("2d----",arr)

1d---- [1 2 3 4 5 6]
2d---- [[1 2 3]
 [4 5 6]]


In [568]:
arr1[3]=700
print("ravel shalow copy==",arr1)
print("2d==",arr)

ravel shalow copy== [  1   2   3 700   5   6]
2d== [[  1   2   3]
 [700   5   6]]


In [244]:
arr1[3]=700
print("flatten shalow copy==",arr1)
print("2d==",arr)

flatten shalow copy== [  1   2   3 700   5   6]
2d== [[  1   2   3]
 [700   5   6]]


In [245]:
arr=np.array([[1,2,3],[4,5,6,]])
arr1=arr.flatten()
print("1d----",arr1)
print("2d----",arr)

1d---- [1 2 3 4 5 6]
2d---- [[1 2 3]
 [4 5 6]]


In [246]:
arr1[3]=700
print("flatten shalow copy==",arr1)
print("2d==",arr)

flatten shalow copy== [  1   2   3 700   5   6]
2d== [[1 2 3]
 [4 5 6]]


In [249]:
arr=np.array([[1,2,3],[4,5,6,]])
arr1=arr
print("1d----",arr1)

print("2d----",arr)

1d---- [[1 2 3]
 [4 5 6]]
2d---- [[1 2 3]
 [4 5 6]]


## arange()

In [251]:
a=np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [252]:
a=np.arange(0,50,5)
a

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [253]:
a=np.arange(1,11)
print(a)
a1=np.arange(1,11,2)
print(a1)
a2=np.arange(1.1,11.2,0.2)
print(a2)
#a2 = np.reshape(2, -1, 2)
#newarr2 = arr.reshape(-1, 2, 2)



[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[ 1.1  1.3  1.5  1.7  1.9  2.1  2.3  2.5  2.7  2.9  3.1  3.3  3.5  3.7
  3.9  4.1  4.3  4.5  4.7  4.9  5.1  5.3  5.5  5.7  5.9  6.1  6.3  6.5
  6.7  6.9  7.1  7.3  7.5  7.7  7.9  8.1  8.3  8.5  8.7  8.9  9.1  9.3
  9.5  9.7  9.9 10.1 10.3 10.5 10.7 10.9 11.1]


#### linespace()   :  creates

In [254]:
a=np.linspace(-30,30,10) ##behave total number has given to advanced in 
a

array([-30.        , -23.33333333, -16.66666667, -10.        ,
        -3.33333333,   3.33333333,  10.        ,  16.66666667,
        23.33333333,  30.        ])

In [255]:
a=np.arange(-30,30,10) ##behaves as stepsize (10)
a

array([-30, -20, -10,   0,  10,  20])

In [256]:
a=np.logspace(-30,30,10) ##show log value of linspace 
a

array([1.00000000e-30, 4.64158883e-24, 2.15443469e-17, 1.00000000e-10,
       4.64158883e-04, 2.15443469e+03, 1.00000000e+10, 4.64158883e+16,
       2.15443469e+23, 1.00000000e+30])

In [257]:
import  numpy as np
a=np.array([[[[[2,3,4,5],[40,50,60,90]]]]])
a

array([[[[[ 2,  3,  4,  5],
          [40, 50, 60, 90]]]]])

In [258]:
a[0][0]

array([[[ 2,  3,  4,  5],
        [40, 50, 60, 90]]])

In [259]:
a=np.arange(3,30,2)  ## 13 15 21 29
a

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [260]:
a[[5,6,9,13]]   # 1d array

array([13, 15, 21, 29])

In [261]:
a[6]

15

In [262]:
a[[5,6,9,-1]]   # 1d array

array([13, 15, 21, 29])

###  some arrays are used for initilisation purpose

* np.empty()
* np.zeros()
* np.ones()

In [263]:
import numpy as np
a=np.empty([2,3])
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [264]:
import numpy as np
a=np.empty([2,3],dtype="int")
a

array([[1, 2, 3],
       [4, 5, 6]])

In [265]:
a=np.zeros([4,4],dtype="int")
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [266]:
a=np.ones([1,4],dtype="int")
a

array([[1, 1, 1, 1]])

In [267]:
a1=np.array([[1,2,3,4],[3,4,5,6],[7,8,9,0]])
a1

a2=np.array([[3,20,5,4],[3,4,50,6],[7,8,7,1]])
a2

array([[ 3, 20,  5,  4],
       [ 3,  4, 50,  6],
       [ 7,  8,  7,  1]])

In [268]:
a1+a2

array([[ 4, 22,  8,  8],
       [ 6,  8, 55, 12],
       [14, 16, 16,  1]])

In [269]:
a1*a2

array([[  3,  40,  15,  16],
       [  9,  16, 250,  36],
       [ 49,  64,  63,   0]])

In [270]:
a1/a2

array([[0.33333333, 0.1       , 0.6       , 1.        ],
       [1.        , 1.        , 0.1       , 1.        ],
       [1.        , 1.        , 1.28571429, 0.        ]])

In [271]:
a1*3

array([[ 3,  6,  9, 12],
       [ 9, 12, 15, 18],
       [21, 24, 27,  0]])

In [272]:
a1>2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True, False]])

In [273]:
a1[a1>2]

array([3, 4, 3, 4, 5, 6, 7, 8, 9])

In [274]:
a1>a2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False]])

In [275]:
a1-a2

array([[ -2, -18,  -2,   0],
       [  0,   0, -45,   0],
       [  0,   0,   2,  -1]])

In [276]:
a1

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [7, 8, 9, 0]])

In [277]:
np.sqrt(a1)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.73205081, 2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        , 0.        ]])

In [278]:
np.sin(a1)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849,  0.        ]])

In [279]:
np.cos(a1)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [-0.9899925 , -0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026,  1.        ]])

In [280]:
import math
a=2.3
math.floor(a)

2

In [281]:
math.ceil(a)

3

In [282]:
a=-3.4
math.floor(a)

-4

In [283]:
math.ceil(a)

-3

In [284]:
a=1.456456
round(a,2)

1.46

In [285]:
a1=np.array(2.3,56.7,-4.5)
np.ceil(a1)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [286]:
a=np.array([[1,2,3,4],[5,6,7,8],[3,4,5,6]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [3, 4, 5, 6]])

In [287]:
np.argmax(a)

7

In [288]:
np.argmin(a)

0

In [289]:
a.max(axis=0)

array([5, 6, 7, 8])

In [290]:
a.max(axis=1)

array([4, 8, 6])

In [291]:
a1.sum()

52

In [292]:
a1.sum(axis=0) ##sum of element by axis vice

array([11, 14, 17, 10])

In [293]:
np.sort(a1,axis=0)

array([[1, 2, 3, 0],
       [3, 4, 5, 4],
       [7, 8, 9, 6]])

In [294]:
np.sort(a1,axis=1)

array([[1, 2, 3, 4],
       [3, 4, 5, 6],
       [0, 7, 8, 9]])

## difference between matrix and array`( matrix is at most 2d whilw  array can be n dimension)

## matrix   (matrix is subclass of array)


In [295]:
import numpy as np
a=np.mat([[1,2],[3,4]])
a

matrix([[1, 2],
        [3, 4]])

In [296]:
a=np.mat([[1,2,5],[7,3,4]])
a

matrix([[1, 2, 5],
        [7, 3, 4]])

In [297]:
a=np.mat([[1,2,3],[3,4,4],[3,4,5]])
a

matrix([[1, 2, 3],
        [3, 4, 4],
        [3, 4, 5]])

In [298]:
a=np.mat([[[1,2,3],[3,4,4],[3,4,5]]])
a

ValueError: matrix must be 2-dimensional

In [299]:
m1=np.array([[1,2],[3,4]])
m2=np.array([[3,4],[8,9]])
m1*m2 




m1=np.mat([[1,2],[3,4]])
m2=np.mat([[3,4],[8,9]])
m1*m2  #


matrix([[19, 22],
        [41, 48]])

In [300]:
a=np.mat([[1,2,3],[3,4,4],[3,4,5]])
a

matrix([[1, 2, 3],
        [3, 4, 4],
        [3, 4, 5]])

In [301]:
a.T

matrix([[1, 3, 3],
        [2, 4, 4],
        [3, 4, 5]])

In [302]:
np.transpose(a)


matrix([[1, 3, 3],
        [2, 4, 4],
        [3, 4, 5]])

In [303]:
np.trace(a)  #(its give sum of diogonal element)

10

## Inverse

In [306]:
a=np.array([[1,2],[3,4]])  
d=np.matrix([[1,2],[3,4]])
print(a.shape)
print(d.shape)
np.linalg.inv(d)



(2, 2)
(2, 2)


matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

## Broadcasting

In [308]:
## case 1  when shape is same 

In [ ]:
a1=np.arange(8).reshape(2,4)
a2=np.arange(8,16).reshape(2,4)
print(a1,"\n\n")
print(a2)
a1+a2

In [309]:
### case: 2  when shape are different
a1=np.arange(9).reshape(3,3)
print(a1)
a1*2  ### scalar

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

##case:2:b whn shapes are different
a1=np.arange(9).reshape(3,3)
a2=np.arange(9).reshape(1,3)
print(a1)
print(a2)

### creat an 3*3 array by all true

In [311]:
import numpy as np
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## extract all odd numbers from array.

In [312]:
arr=np.arange(20)
arr 
a=arr[arr%2==0]      #for even
a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [313]:
a=arr[arr%2==1]       # for odd
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

## repalce all odd num by (-1).

In [314]:
arr[arr%2==1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16,
       -1, 18, -1])

## replace all odd num by (-1) without chnging array.

In [315]:
np.where(arr%2==1,-1,arr)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16,
       -1, 18, -1])

## convert 1D array in 2D arry with 2 rows.

In [316]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

##  find tha common items from A nd C.

In [318]:
a=np.array([1,2,3,4,5,6,7,8,9,5])
c=np.array([11,2,12,14,15,16,17,18,5])
np.intersect1d(a,c)

array([2, 5])

## removes all tha items frm a whuch are c.

In [319]:
np.setdiff1d(a,c)

array([1, 3, 4, 6, 7, 8, 9])

## find all tha num btw 5 and 10.

In [320]:
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [323]:
a[(a>=5)&(a<=10)]

array([ 5,  6,  7,  8,  9, 10])

In [324]:
np.where((a>=5)&(a<=10))

(array([ 5,  6,  7,  8,  9, 10], dtype=int64),)

## swap column 2 by 1.

In [326]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [327]:
a[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

## swap rows 1 to 2 

In [328]:
a[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

## reverse tha rows of 2D arr and coumn too.

In [332]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [333]:
a[::-1]   ## row

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [334]:
a[:,1]    ## column

array([1, 4, 7])

##  create a 2D array of 5*3 to random decimal number  btw 5 and 10

In [335]:
np.random.uniform(5,10,size=(5,3))

array([[7.98884243, 5.39496231, 9.5806239 ],
       [8.48821906, 8.98347312, 7.91530997],
       [8.28117481, 8.7678441 , 7.50663854],
       [6.61140546, 6.74516424, 7.65277361],
       [7.95477834, 8.2291896 , 6.93829241]])

In [336]:
import numpy as np
a1=np.array([[1,2,3,4,5],[5,6,7,8,9],[2,3,4,5,6]])
a1
a1.shape

(3, 5)

In [337]:
a1

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6]])

In [338]:
a1[:,::4]

array([[1, 5],
       [5, 9],
       [2, 6]])

In [339]:
a1[:,::4]

array([[1, 5],
       [5, 9],
       [2, 6]])

In [340]:
a1[:-1]

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9]])

### create an array of 10 zeros

In [342]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### create an array of 10 ones

In [343]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### create an array of  10  fives.

In [344]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

### create an array of interger 10 to 50.

In [345]:
a=np.arange(10,51)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


### createa an array of alll tha evn numbers frm 10 to 50.

In [346]:
a=np.arange(10,51)
a1=a[a%2==0]
print(a1)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [347]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

### create an 3*3 matrux with values  ranging from 0 to 8.

In [348]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### create an 3*3 identity matrix.

In [349]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [350]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### using numpy generate random no. btw 0 to 1.

In [351]:
np.random.rand(1)

array([0.62270804])

###  generate 25 random sample from standard normal distribution.

In [352]:
np.random.randn(25)

array([-0.33223146, -0.06681175,  0.48733394, -0.37580328, -0.02701958,
        2.39210557, -0.84153742, -1.14367325, -1.78808885, -0.78176912,
       -0.20092044, -3.41561511,  2.17583335, -1.23140101, -0.63310605,
        0.80880302,  0.88525687, -1.31003845, -1.40519252, -0.79253205,
        0.61595281,  0.69944817,  0.96868356, -2.19106345,  0.10217072])

###  create  an array of 20 linearly spaced  number btw 0 and 1.

In [353]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

###  indexing

In [354]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [355]:
a[2:,2:]

array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [356]:
a[3,4]

20

In [357]:
a[2,2]

13

## create an array of shape 3*2*3,

In [364]:
import numpy as np
a=np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
a

array([[[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3]]])

In [365]:
a.shape

(3, 2, 3)

In [366]:
np.zeros([3,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### create a vetor of size 10

In [370]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## create an array with random values of shape

In [371]:
np.random.randn(3,3)   ####31

array([[ 2.2483538 , -0.55874098,  1.21003809],
       [ 0.24817992, -1.17432594, -0.36045466],
       [-1.3015913 , -0.89377319, -2.01334066]])

In [372]:
np.random.random()   #### (we get one value in btw 1 and 0 ater every we tha diffrent value)

0.02140951029371596

In [373]:
np.random.seed(2) ## any value u cn take 
np.random.random()  #( generate same random value btw 0 and 1 on excuation)

0.43599490214200376

In [374]:
## generate singe random value with n given range
np.random.uniform(10,30) # atart with 10 and ends with 30

10.518524636557826

In [375]:
### generate random no.  of certain length i.e  arrray with given range
import numpy as np
np.random.uniform(1,100,10)

array([55.41658531, 44.09691687, 42.61641241, 33.70314728, 21.26021477,
       62.30782567, 30.66581269, 27.41590024, 62.49224944, 53.38506733])

In [376]:
np.random.uniform(1,100,10).reshape(5,2)

array([[14.32341459, 51.84423401],
       [19.2595467 , 78.74817963],
       [85.54355397, 49.9294469 ],
       [84.80958705,  8.88490222],
       [51.01936292,  7.46336393]])

In [377]:
np.random.uniform(1,100,10).reshape(2,5)

array([[43.38411043, 10.55656065, 13.5888372 , 60.07778559, 23.37518806],
       [11.58762275, 22.8103145 , 35.63280222, 47.31096097, 20.9725794 ]])

In [378]:
np.random.uniform(1,100,10).reshape(10,1)

array([[64.4002658 ],
       [48.82391372],
       [51.01843528],
       [39.30237246],
       [79.57010799],
       [58.42041371],
       [17.06756125],
       [70.37448231],
       [96.49055693],
       [50.50082776]])

In [379]:
np.random.randint(1,10,5)  # 1d arry

array([1, 3, 9, 9, 3])

In [380]:
np.random.randint(1,10,5).reshape(1,5)  # 2d arry

array([[7, 6, 7, 7, 7]])

In [381]:
np.random.randint(1,10,5).reshape(5,1)  # 2d arry

array([[4],
       [9],
       [3],
       [2],
       [5]])

In [382]:
np.random.randint(1,10,15).reshape(3,5)  # 2 darry

array([[9, 2, 7, 6, 2],
       [3, 5, 8, 7, 5],
       [6, 9, 4, 1, 1]])

## NORMAL DISTRIBUTION  (symetric)

In [386]:
a2=np.random.normal(loc=5,scale=7,size=9)
a2

array([ -2.7460184 ,   0.06692632,   0.25731357,  10.45110976,
         7.45287202,   5.15468743,   0.32741272,   8.92564247,
       -11.66556944])

In [387]:
a2=np.random.normal(loc=10,scale=4,size=1000)
a2

array([ 8.54864839,  6.67954271,  0.28499756, 10.51287115,  0.10525521,
       11.50469179, 15.86423703, 12.42641142, 10.25011107,  9.16098702,
       18.27168418, 10.58683868,  8.59465198, 15.02762342, 14.20877324,
        5.11913356,  5.02722486,  8.10809496, 11.57898571, 14.77403993,
       13.42949728, 13.21913507,  8.19916626,  6.60469286, 13.88252011,
        7.13534956, 13.29525007, 11.2766987 ,  7.57413469, 10.33488646,
       13.26580908, 10.53233888,  5.51593311, 14.07314983, 13.10986544,
        8.12948551,  6.4801163 ,  7.52529438, 10.75787548, 10.03550876,
       12.80116948, 14.58506903,  8.98477179, -1.20885323,  4.91805313,
       11.44507337, 10.80955173, 12.00428241,  9.97261969,  7.00047686,
       12.49303321,  9.08867946,  8.51047416, 10.79240981, 11.97845947,
       12.39632873,  6.16950201, 10.62682662,  9.68502316,  0.97151717,
       11.60520299, -1.48683218, 11.37845287, 11.49997414, 10.71028526,
        2.2350761 ,  8.28610006,  9.90918785,  8.5994796 , 10.62

In [388]:
print(np.mean(a2),np.median(a2))

9.851206681401036 9.899164894819213


In [389]:
import statistics
statistics.mode(a2)

8.548648387309754

## generate tha random  value that form normal standarisation appoximately to zero and std is appp(to 1)

In [390]:
a=np.random.randn(1000)
a

array([-1.23170807e+00, -4.26693027e-01, -2.94036017e-01,  7.83946928e-01,
        9.23302953e-01,  4.49854283e-01, -5.04616942e-01,  1.54111028e+00,
       -3.31337629e-01,  6.27368612e-01, -5.52166251e-01, -2.47825339e-01,
       -5.11848032e-01, -2.02074982e+00, -1.51470895e+00, -1.01314713e+00,
       -4.10937078e-01, -8.21527881e-01,  2.54515655e-01, -1.65751603e-01,
       -1.26213568e+00, -5.26299870e-01,  2.68433712e-01, -5.87263043e-01,
       -2.30642249e-01,  1.28689410e-03, -6.22807119e-01, -9.28858285e-01,
       -1.64682289e+00, -4.48235802e-01,  6.48456773e-01, -2.63644132e-02,
       -6.64180539e-01,  1.61512076e+00,  8.83618824e-01,  5.10387648e-01,
       -1.18335145e+00,  7.03185652e-01, -1.84847998e-01, -1.11245618e-01,
        3.92202246e-01, -1.70411775e+00, -7.53776019e-01,  1.30519259e+00,
       -7.62899717e-02, -3.71456570e-01, -2.70755986e-01,  1.38420648e+00,
       -1.70153018e+00, -2.00316090e+00, -1.54262776e+00,  1.09384259e-01,
        7.85450079e-01,  

In [391]:
np.mean(a)  ### approx to 0

0.010246179695024902

In [392]:
np.std(a)   ### approx to 1

0.9795748425744399

In [393]:
np.random.random_sample((4,7))   ### generte random sample of size 4*7 bte 0 to 1

array([[0.53185522, 0.86586477, 0.86032423, 0.72475914, 0.02058719,
        0.39987575, 0.39622064],
       [0.25312393, 0.9605086 , 0.57909185, 0.17201761, 0.72192772,
        0.45090886, 0.77822767],
       [0.16475718, 0.22587834, 0.12593046, 0.95873594, 0.82898405,
        0.98873624, 0.9297042 ],
       [0.40460812, 0.64263674, 0.19794177, 0.67895279, 0.63363189,
        0.90791268, 0.62221058]])

## create an identity matrix

In [394]:
import numpy as np
a=np.array([[1,2,3],[1,2,3],[1,2,3]])
a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [395]:
np.diag(a,k=-1)

array([1, 2])

In [396]:
np.diag(a,k=1)

array([2, 3])

In [397]:
np.diag(a,k=2)

array([3])

In [398]:
a=np.diag(a,k=0)  ##  make rest of tha element zero only given diagonal elements 
a

array([1, 2, 3])

In [399]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [400]:
a=np.eye(3,k=0)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [401]:
a=np.eye(3,k=1)
a

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [402]:
a=np.eye(3,k=-1)
a

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [403]:
a=np.eye(3,k=2)
a

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [404]:
a=np.eye(3,k=-2)
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.]])

### diagflat: for creating array means tha element is to be placed diagonaly based odn tha

In [406]:
import numpy as np
a2=np.diagflat([1,2,3,4],k=0)
a2

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [407]:
import numpy as np
a2=np.diagflat([1,2,3,4],k=1)
a2

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [408]:
a=np.array([[1,2,3],[12,3,5],[4,5,6]])
a

array([[ 1,  2,  3],
       [12,  3,  5],
       [ 4,  5,  6]])

## From function

In [409]:
np.fromfunction(lambda i,j:i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [410]:
np.fromfunction(lambda i,j:i+j,(4,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

In [411]:
np.fromfunction(lambda i,j:i-j,(4,4))

array([[ 0., -1., -2., -3.],
       [ 1.,  0., -1., -2.],
       [ 2.,  1.,  0., -1.],
       [ 3.,  2.,  1.,  0.]])